# Generated by Django 4.1.3 on 2022-11-09 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(choices=[('A', 'Amplifier'), ('D', 'DAC')], default='A', max_length=1)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Headphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('equipment', models.ManyToManyField(to='main_app.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Listened',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Last Session')),
                ('time_hrs', models.IntegerField(default=0)),
                ('time_mins', models.IntegerField(default=0)),
                ('headphone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.headphone')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
