# Generated by Django 4.1.3 on 2022-11-09 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headphone',
            name='equipment',
            field=models.ManyToManyField(to='main_app.equipment'),
        ),
    ]
