# Generated by Django 4.1.3 on 2022-11-07 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listened',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Last Session')),
                ('time', models.IntegerField()),
                ('headphone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.headphone')),
            ],
        ),
    ]
