# Generated by Django 4.1.3 on 2022-11-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_listened'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listened',
            name='time',
        ),
        migrations.AddField(
            model_name='listened',
            name='time_hrs',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='listened',
            name='time_mins',
            field=models.IntegerField(default=1),
        ),
    ]
